version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  
    depends_on:
      - kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    command: ["sh", "-c", "sleep 15 && kafka-topics --create --zookeeper zookeeper:2181 --topic myTopic --partitions 1 --replication-factor 1"]
    ports:
      - "9092:9092"  
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  
  

  redis:
    build: ./redis  
    ports:
      - "6379:6379" 
  spring-boot-app:
    build: .  
    ports:
      - "8080:8080"  
    environment:
      REDIS_HOST: redis  
      REDIS_PORT: 6379  